name: Tauri

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Need
      run: npm install
    - name: Build
      run: npm run tauri build
    - uses: actions/upload-artifact@v2
      with:
        name: lunar_chat_bundle
        path: src-tauri/target/release/bundle